### ISSUE TITLE
maybe one bug in your code

### ISSUE THREAD

**Issue by freedani** [qzane/SPlayerSubDownloader#1]
Hello, thanks for your code help me downloading the subs.
I'm using mac with python 2.7.10.
When I run your code, it was an error
  File "SPlayerSub.py", line 51, in fileHash
    for i in [4096, int(length*2/3), int(length/3), length-8192]:
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
I change line 49
`length = file.seek(0,2)`
to
```
file.seek(0,2)
length = file.tell()
```
and it works.

**Comment by qzane** [comment]
Thanks a lot for your report. It seems that we got a difference of file object between Python3 and Python2. I'll update the code accordingly.
